### PR TITLE
External files to vault and auto syntax highlight + little fixes

### PR DESCRIPTION
**Pull request by 1C0D**
- now accepting external files 
- auto syntax highlighting from path extension
- same code embedding error when not finding the file (improves the presentation)
[demo](https://youtu.be/cDhnNdyxSjE)

### CODE REVIEW

**Comment by 1C0D** [comment]
You should add a release too with the main.js file (doing a build) and the manifest.
demo

**Comment by sveitech** [comment]
Thank you for your contribution :) Sorry, I do not know what "add a release" means. Can you elaborate?

**Comment by 1C0D** [comment]
you can check this too https://marcus.se.net/obsidian-plugin-docs/publishing/submit-your-plugin

**Comment by sveitech** [comment]
Thank you for the descriptions. Is there a reason you closed this pull request?

**Comment by 1C0D** [comment]
There is another official plugin for the same thing. Maybe he was inspired by your code. Dut it's not the same approach, finally. But this is full of bugs and hard to use. I developed a new approach using your first approach. it's easier to use. But coming to add a tittle like he did in the other plugin, there are some problems of actualization. Still studying the question. But I noticed this is really hard to communicate on github because you are never sure an author is still following his repos. And doing changes on an already done plugin is a constraint. Maybe the whole structure needs to be changed.  I did a try on this repo to push things further. you can use it like this if no ext is given it will use the file extension. the language of the block code is "embed" then on the same line you can provide an ext after a space and then the "title" (between "") if not ext it will see the title is at the 2nde position
embed py "title" or embed "title" or just embed
then in the code block the path. 
a modal could be added to create directly the code block from a selection (the path)
some html paths like in the other plugin

actual bugs (from last night)
the title for the moment is only showed after clicking on the content of the block code
the indication language (when specified) is not appearing in all code block when several code blocks 
https://github.com/1C0D/easy-embed-code

**Pull request closed without merging**
